spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&characterEncoding=utf-8
    username: root
    password: root

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout:  0

mybatis:
  type-aliases-package: com.imd.entity
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
  check-config-location: true


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true


